### ISSUE TITLE
[Bugs] Depth strider and aqua affinity and elytra are not work

### ISSUE THREAD

**Issue by HuJK** [atesin/showskin#2]
Depth strider and aqua affinity and elytra are not work when my armor is hidden.

I guess this stuff are calculate in client, so if server tells my client I didn't wear anything, my client will not allow me to fly?

Is it possible that always show my armor in my client, but hide to all other players? So that my client can deal with some enchantment that processed in client?

**Comment by atesin** [comment]
hi.. thanks for your interest

the armor actually can't be turned invisible in multiplayer, it is technically impossible by the way the game works

but instead i found this can be simulated by "hiding" the armor it in another place in the server, and briefly re-equip when PHYSICAL damage is detected (i.e.: damage can be reduced by armor value)

so if you want to benefit with underwater breath or elytra or some other armor effect, you should explicitly "unhide" your armor

read more here = https://dev.bukkit.org/projects/invisible-armor
